[networks.eos]
endpoints = ["https://eos.hyperion.eosrio.io",]
consensus_threshold = 10
events = [
  ["eosio.token", "transfer"],
]
[networks.ethereum]
endpoints = ["https://eth.public-rpc.com",]
consensus_threshold = 10
events = [
  [
    "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
  ]
]
