[package]
name = "attestation"
version = "0.1.0"
edition = "2021"
authors = ["Ulisse Bordignon"]
description = "Very thin wrapper around the NSM to be called by the Event Attestator Nitro"

[dependencies]
aws-nitro-enclaves-nsm-api = "0.4.0"
hex = "0.4.3"
serde_bytes = "0.11.15"
